import { Countdown } from "./components/Countdown";
import { Faq } from "./components/Faq";
import { MobileMenu } from "./components/MobileMenu";
import { siteConfig } from "./site-config";
import Image from "next/image";

const educationStages = [
  { number: "00", grade: "0-sinf", title: "Ishonchli boshlanish", copy: "Maktabga tayyorlov, nutq, mantiq va ijtimoiy ko‘nikmalar — o‘yin orqali, bosimsiz." },
  { number: "08", grade: "1–8-sinflar", title: "Chuqur bilim", copy: "Asosiy fanlar, tillar va amaliy mashg‘ulotlar uyg‘unligida mustahkam poydevor." },
  { number: "11", grade: "9–11-sinflar", title: "Aniq yo‘nalish", copy: "Kasb tanlovi, milliy sertifikat, SAT, IELTS va IT bo‘yicha maqsadli tayyorgarlik." },
];
const systems = [
  ["01", "Monitoring test", "Har oy 100 ballik tizimda bilim darajasi va o‘sish dinamikasi."],
  ["02", "EDU COIN", "Faollik, tashabbus va natijani real mukofotga aylantiruvchi motivatsiya."],
  ["03", "Xulq-atvor reytingi", "Intizom, mas’uliyat va ijobiy odatlarni shaffof kuzatish."],
  ["04", "Ota-ona uchun CRM", "Davomat, natija va rivojlanishni bitta qulay platformada ko‘rish."],
];
const subjects = ["Matematika", "Biologiya", "Kimyo", "Fizika", "Tarix", "Ona tili", "Ingliz tili", "IT & robototexnika"];
const languages = ["EN", "RU", "AR", "ZH", "KO", "DE"];

export default function Home() {
  return <main>
    <div className="announcement"><div className="container announcement__inner"><div><span className="live-dot" /> <strong>18-avgust • 09:00</strong> — EURO SCHOOL musobaqasi</div><Countdown target={siteConfig.event.dateTime} compact /><a href="#musobaqa">Batafsil <span>↘</span></a></div></div>
    <header className="site-header"><div className="container nav-wrap"><a className="brand" href="#top" aria-label="Euro School bosh sahifa"><Image src="/assets/euro-school-logo.png" width={2048} height={651} alt="EURO SCHOOL" priority /></a><nav className="desktop-nav" aria-label="Asosiy navigatsiya"><a href="#maktab">Maktab</a><a href="#talim">Ta’lim</a><a href="#imkoniyatlar">Imkoniyatlar</a><a href="#qabul">Qabul</a><a href="#savollar">Savollar</a></nav><div className="nav-actions"><a className="phone-link" href={`tel:${siteConfig.phoneHref}`}>{siteConfig.phoneDisplay}</a><a className="button button--dark" href="#qabul">Qabulga yozilish <span>↗</span></a></div><MobileMenu /></div></header>

    <section className="hero" id="top"><div className="container hero__grid"><div className="hero__copy"><div className="eyebrow"><span>2026–2027</span> o‘quv yili uchun qabul ochiq</div><h1>Farzandingizning<br /><em>kelajagi</em> bugundan<br />boshlanadi.</h1><p className="hero__lead">Xalqaro ta’lim, milliy qadriyatlar va har bir bolaga individual e’tibor — barchasi bir maktabda.</p><div className="hero__buttons"><a className="button button--primary button--large" href={`tel:${siteConfig.phoneHref}`}>Qabul bo‘yicha bog‘lanish <span>↗</span></a><a className="text-link" href="#maktab">Maktabni kashf eting <span>↓</span></a></div><div className="limited"><span className="limited__icon">!</span><div><strong>{siteConfig.limitedSeatsText}</strong><small>Qabul yakunlanishidan oldin joyingizni band qiling</small></div></div></div><div className="hero__visual"><div className="hero__photo"><Image src="/assets/euro-school-building.png" width={1280} height={720} alt="EURO SCHOOL maktab binosi" priority /></div><div className="hero__badge"><span>0–11</span><small>sinflar uchun<br />zamonaviy ta’lim</small></div><div className="hero__quote">“Biz faqat dars bermaymiz — <strong>kelajak liderlarini</strong> tarbiyalaymiz.”</div></div></div><div className="container stat-line"><div><strong>06</strong><span>xorijiy til</span></div><div><strong>100</strong><span>ballik monitoring</span></div><div><strong>03</strong><span>mahal sog‘lom ovqat</span></div><div><strong>01</strong><span>farzandingiz uchun aniq yo‘l</span></div></div></section>

    <section className="event-section" id="musobaqa"><div className="container event-card"><div className="event-card__meta"><span>Yaqin tadbir</span><strong>18<br />AVG</strong><small>09:00</small></div><div className="event-card__copy"><p className="kicker">Bilim. Jasorat. G‘alaba.</p><h2>EURO SCHOOL<br />musobaqasi</h2><p>Maktab muhitini yaqindan ko‘ring, yangi imkoniyatlarni kashf eting va katta maqsadlar sari ilk qadamni qo‘ying.</p></div><div className="event-card__timer"><p>Boshlanishiga qoldi</p><Countdown target={siteConfig.event.dateTime} /><a className="button button--light" href={`tel:${siteConfig.phoneHref}`}>Ishtirok etish <span>↗</span></a></div><div className="event-orbit" aria-hidden="true"><span>EURO</span><span>SCHOOL</span><span>2026</span></div></div></section>

    <section className="section intro" id="maktab"><div className="container split-heading"><div><p className="section-label">01 / Maktab haqida</p><h2>Oddiy maktab emas.<br /><span>Yangi avlod muhiti.</span></h2></div><div className="intro__copy"><p>EURO SCHOOL — bolaga faqat bilim emas, fikrlash, tanlash va o‘z imkoniyatiga ishonishni o‘rgatadigan zamonaviy maktab.</p><p>Biz har bir o‘quvchining kuchli tomonini ko‘ramiz va uni aniq natijaga olib boradigan ta’lim yo‘lini quramiz.</p><div className="principles"><span>Chuqur bilim</span><span>Erkin fikr</span><span>Milliy qadriyat</span><span>Global imkoniyat</span></div></div></div></section>

    <section className="section stages" id="talim"><div className="container"><div className="section-top"><div><p className="section-label">02 / Ta’lim yo‘li</p><h2>Har yoshga mos.<br /><span>Har maqsadga aniq.</span></h2></div><div className="education-intro"><p>0-sinfdan universitetgacha — izchil, tushunarli va natijaga yo‘naltirilgan rivojlanish yo‘li.</p><a className="program-link" href={siteConfig.educationProjectPdf} target="_blank" rel="noreferrer"><span className="program-link__icon">PDF</span><span><strong>O‘quv dasturimiz bilan tanishing</strong><small>EURO SCHOOL ta’lim loyihasini ochish</small></span><b>↗</b></a></div></div><div className="stage-grid">{educationStages.map(stage => <article className="stage-card" key={stage.grade}><span className="stage-card__number">{stage.number}</span><p>{stage.grade}</p><h3>{stage.title}</h3><div className="stage-card__line" /><p className="stage-card__copy">{stage.copy}</p><a href="#qabul" aria-label={`${stage.grade} qabuli haqida`}>Qabul haqida <span>↗</span></a></article>)}</div></div></section>

    <section className="section system-section" id="imkoniyatlar"><div className="container"><div className="system-head"><p className="section-label section-label--light">03 / EURO tizimi</p><h2>Natija tasodif emas.<br /><span>U — tizim.</span></h2><p>O‘quvchi, ota-ona va maktab bir maqsad atrofida ishlaganda o‘sish ko‘rinadi, o‘lchanadi va qadrlanadi.</p></div><div className="system-grid">{systems.map(([number,title,copy]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section knowledge"><div className="container"><div className="knowledge__grid"><div className="knowledge__statement"><p className="section-label">04 / Chuqur bilim</p><h2>Fanlarni yodlamaymiz.<br /><span>Tushunamiz va qo‘llaymiz.</span></h2><p>Nazariya, amaliyot va mantiqiy fikrlashni birlashtiradigan darslar farzandingizni nafaqat imtihonga, balki hayotga tayyorlaydi.</p></div><div className="subject-list">{subjects.map((subject,index) => <div key={subject}><span>{String(index+1).padStart(2,"0")}</span><strong>{subject}</strong><i>↗</i></div>)}</div></div></div></section>

    <section className="section global-section"><div className="container global-card"><div><p className="section-label section-label--light">05 / Global kelajak</p><h2>Dunyo bilan<br /><span>bir tilda.</span></h2><p>Til — fan emas, yangi imkoniyatlarga ochiladigan eshik. EURO SCHOOL’da o‘quvchilar xalqaro muloqotga tayyorlanadi.</p><div className="language-row">{languages.map(lang => <span key={lang}>{lang}</span>)}</div></div><div className="global-paths"><article><span>SAT</span><h3>Xalqaro universitetlar</h3><p>Akademik ingliz tili, matematika va tanqidiy fikrlash.</p></article><article><span>IELTS</span><h3>Erkin muloqot</h3><p>Listening, reading, writing va speaking ko‘nikmalari.</p></article><article><span>IT</span><h3>Kelajak kasblari</h3><p>Dasturlash, web, algoritmik fikrlash va raqamli savodxonlik.</p></article></div></div></section>

    <section className="section parent-section"><div className="container parent-grid"><div><p className="section-label">06 / Ota-onalar uchun</p><h2>Siz xotirjam.<br /><span>Farzandingiz nazoratda.</span></h2><p className="parent-lead">Har bir muhim natija siz uchun ochiq va tushunarli.</p></div><div className="parent-list"><div><b>01</b><span><strong>Ochiq monitoring</strong><small>Bilim, davomat va xulq-atvor dinamikasi</small></span></div><div><b>02</b><span><strong>Individual yondashuv</strong><small>Har bir bolaning kuchli tomoni uchun alohida e’tibor</small></span></div><div><b>03</b><span><strong>Sog‘lom muhit</strong><small>Uch mahal ovqat, sport va psixologik qo‘llab-quvvatlash</small></span></div></div></div></section>

    <section className="section admission" id="qabul"><div className="container admission-card"><div className="admission-card__copy"><div className="eyebrow eyebrow--light"><span>Qabul ochiq</span> joylar soni cheklangan</div><h2>Farzandingiz uchun<br />to‘g‘ri maktabni<br /><em>bugun tanlang.</em></h2><p>Biz bilan bog‘laning — savollaringizga javob beramiz va maktab bilan tanishuv vaqtini belgilaymiz.</p><div className="admission-actions"><a className="button button--gold button--large" href={`tel:${siteConfig.phoneHref}`}>Qo‘ng‘iroq qilish <span>↗</span></a><a className="button button--outline-light button--large" href={siteConfig.social.telegram} target="_blank" rel="noreferrer">Telegram <span>↗</span></a></div></div><div className="admission-steps"><p>Qabul jarayoni</p><ol><li><span>01</span><div><strong>Bog‘lanish</strong><small>Telefon yoki Telegram orqali</small></div></li><li><span>02</span><div><strong>Maktab bilan tanishuv</strong><small>Muhit, dastur va imkoniyatlarni ko‘ring</small></div></li><li><span>03</span><div><strong>Diagnostika va suhbat</strong><small>Farzandingiz uchun mos yo‘lni aniqlaymiz</small></div></li><li><span>04</span><div><strong>Qabul</strong><small>Hujjatlarni rasmiylashtirish va start</small></div></li></ol></div></div></section>

    <section className="section faq-section" id="savollar"><div className="container faq-grid"><div><p className="section-label">07 / Savol-javob</p><h2>Ota-onalar ko‘p<br /><span>so‘raydigan savollar.</span></h2><p>Javob topilmadimi? <a href={`tel:${siteConfig.phoneHref}`}>{siteConfig.phoneDisplay}</a> raqamiga qo‘ng‘iroq qiling.</p></div><Faq /></div></section>

    <section className="location-section"><div className="container"><div className="location-heading"><p className="section-label">Maktab manzili</p><h2>Bizni xaritada toping.</h2></div><div className="location-card"><div className="location-map"><iframe title="EURO SCHOOL lokatsiyasi" src="https://www.google.com/maps?q=40.65533,71.744331&z=16&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div><div className="location-bar"><div className="location-bar__name"><span className="location-pin" aria-hidden="true">●</span><div><strong>EURO SCHOOL</strong><small>{siteConfig.location}</small></div></div><a className="button button--gold" href={siteConfig.mapUrl} target="_blank" rel="noreferrer">Yo‘lni ko‘rsatish <span>↗</span></a></div></div></div></section>

    <footer><div className="container footer-top"><div className="footer-brand"><Image src="/assets/euro-school-logo.png" width={2048} height={651} alt="EURO SCHOOL" /><p>Xalqaro ta’lim va milliy<br />qadriyatlar uyg‘unligi.</p></div><div><p className="footer-label">Navigatsiya</p><a href="#maktab">Maktab haqida</a><a href="#talim">Ta’lim dasturi</a><a href="#imkoniyatlar">Imkoniyatlar</a><a href="#qabul">Qabul</a></div><div><p className="footer-label">Bog‘lanish</p><a href={`tel:${siteConfig.phoneHref}`}>{siteConfig.phoneDisplay}</a><a href={siteConfig.mapUrl} target="_blank" rel="noreferrer">{siteConfig.location} ↗</a></div><div><p className="footer-label">Ijtimoiy tarmoqlar</p><a href={siteConfig.social.telegram} target="_blank" rel="noreferrer">Telegram ↗</a><a href={siteConfig.social.instagram} target="_blank" rel="noreferrer">Instagram ↗</a><a href={siteConfig.social.youtube} target="_blank" rel="noreferrer">YouTube ↗</a></div></div><div className="container footer-bottom"><span>© 2026 EURO SCHOOL. Barcha huquqlar himoyalangan.</span><a href="#top">Yuqoriga ↑</a></div></footer>
    <a className="floating-call" href={`tel:${siteConfig.phoneHref}`} aria-label="EURO SCHOOL ga qo‘ng‘iroq qilish"><span>☎</span><b>Qo‘ng‘iroq</b></a>
  </main>;
}
